# Generated by Django 4.2.30 on 2026-04-22 18:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('irg_gic', '0002_household_redemption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giccertificate',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='giccertificate',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('MATURED', 'Matured'), ('REDEEMED', 'Redeemed')], default='ACTIVE', max_length=15),
        ),
        migrations.AlterField(
            model_name='gicredemption',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='gicrevenuedistribution',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='gicrevenuedistribution',
            name='stream',
            field=models.CharField(choices=[('CORPUS', 'Corpus Returns'), ('TRADING', 'Trading Fees'), ('APPRECIATION', 'Gold Appreciation')], max_length=15),
        ),
        migrations.AlterField(
            model_name='householdregistration',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
