# Generated by Django 4.2.30 on 2026-04-22 18:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('irg_jdb', '0002_design_license'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copyright',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='design',
            name='category',
            field=models.CharField(choices=[('RING', 'Ring'), ('NECKLACE', 'Necklace'), ('BRACELET', 'Bracelet'), ('EARRING', 'Earring'), ('PENDANT', 'Pendant'), ('BANGLE', 'Bangle'), ('OTHER', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='design',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='design',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=15),
        ),
        migrations.AlterField(
            model_name='designlicense',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='designorder',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='designorder',
            name='status',
            field=models.CharField(choices=[('PLACED', 'Placed'), ('ACCEPTED', 'Accepted'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PLACED', max_length=15),
        ),
        migrations.AlterField(
            model_name='royaltypayment',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
