# Generated by Django 4.2.30 on 2026-04-21 07:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CorpusFund',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_balance', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('physical_gold_value', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('other_investments_value', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('gold_grams_held', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('blockchain_address', models.CharField(max_length=66)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('jeweler', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='corpus_fund', to='core.jewelerprofile')),
            ],
            options={
                'db_table': 'corpus_fund',
            },
        ),
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('settlement_type', models.CharField(choices=[('BUYBACK', 'Buyback Payment'), ('BONUS', 'Bonus Distribution'), ('WITHDRAWAL', 'Withdrawal')], max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('reference_id', models.CharField(max_length=100)),
                ('settlement_tx_hash', models.CharField(max_length=66)),
                ('settled_at', models.DateTimeField(auto_now_add=True)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('corpus_fund', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlements', to='corpus.corpusfund')),
            ],
            options={
                'db_table': 'corpus_settlement',
            },
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('investment_type', models.CharField(choices=[('PHYSICAL_GOLD', 'Physical Gold'), ('GOLD_ETF', 'Gold ETF'), ('GOVT_BONDS', 'Government Bonds'), ('FIXED_DEPOSIT', 'Fixed Deposit')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('current_value', models.DecimalField(decimal_places=2, max_digits=18)),
                ('returns_earned', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('MATURED', 'Matured'), ('LIQUIDATED', 'Liquidated')], default='ACTIVE', max_length=15)),
                ('invested_at', models.DateTimeField(auto_now_add=True)),
                ('maturity_date', models.DateField(blank=True, null=True)),
                ('corpus_fund', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='investments', to='corpus.corpusfund')),
            ],
            options={
                'db_table': 'corpus_investment',
            },
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('deposit_type', models.CharField(choices=[('MINTING', 'Minting Contribution'), ('JR_ISSUANCE', 'JR Issuance'), ('VOLUNTARY', 'Voluntary'), ('PENALTY', 'Penalty')], max_length=15)),
                ('reference_id', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('FAILED', 'Failed')], default='PENDING', max_length=15)),
                ('deposit_tx_hash', models.CharField(blank=True, max_length=66, null=True)),
                ('deposited_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('corpus_fund', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deposits', to='corpus.corpusfund')),
                ('depositor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'corpus_deposit',
            },
        ),
    ]
