"""
IRG Chain 888101 — On-chain transaction audit log.

Every call the Django backend makes to the submission middleware creates
(or updates) a row here. This is the canonical record:
  * if middleware crashes or drops a response, we still know a tx was attempted
  * if we need to reconcile against the chain, we iterate this table
  * a single client_tx_id row can move SUBMITTED -> CONFIRMED -> FINAL
    as the chain confirms and finalises

IPR Owner: Rohit Tidke | Exclusively assigned to: Intech Research Group
"""
from django.conf import settings
from django.db import models


class TxAuditLog(models.Model):
    STATUS_CHOICES = [
        ('PENDING', 'Pending — queued in backend, not yet sent to middleware'),
        ('SUBMITTED', 'Submitted to middleware, awaiting chain receipt'),
        ('CONFIRMED', 'Included in a block on IRG Chain 888101'),
        ('FINAL', 'Finalised (N confirmations deep)'),
        ('FAILED', 'Middleware rejected or chain reverted'),
        ('SIMULATED', 'Dev/test path — no real on-chain write'),
    ]

    MODE_CHOICES = [
        ('raw', 'Raw — pre-signed by user device'),
        ('system', 'System — signed by backend operator key'),
    ]

    # Idempotency key — generated by the backend before submission.
    # Same key = same logical operation; safe to retry on transient failure.
    client_tx_id = models.CharField(max_length=80, unique=True, db_index=True)

    # Which app + action caused this tx, for audit/search.
    module = models.CharField(max_length=40, db_index=True)    # irg_gdp, irg_jr, corpus, ...
    action = models.CharField(max_length=60, db_index=True)    # mint_gdp, issue_jr, ...
    mode = models.CharField(max_length=10, choices=MODE_CHOICES, default='system')

    # Who triggered it in the application domain.
    actor = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL, null=True, blank=True,
        related_name='chain_tx_audits',
    )

    # Ethereum-side fields.
    chain_id = models.IntegerField(default=888101)
    to_address = models.CharField(max_length=66, blank=True)
    value_wei = models.CharField(max_length=80, blank=True, default='0')
    data_hash = models.CharField(max_length=66, blank=True)     # sha256 of calldata, not the calldata itself
    tx_hash = models.CharField(max_length=66, blank=True, db_index=True)
    block_number = models.BigIntegerField(null=True, blank=True)

    # Application-side context (what this tx is *about*).
    # Free-form but searchable; keep PII out.
    meta = models.JSONField(default=dict, blank=True)

    status = models.CharField(max_length=12, choices=STATUS_CHOICES, default='PENDING', db_index=True)
    last_error = models.TextField(blank=True)
    retries = models.PositiveSmallIntegerField(default=0)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    confirmed_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        db_table = 'chain_tx_audit_log'
        ordering = ['-created_at']
        indexes = [
            models.Index(fields=['module', 'action']),
            models.Index(fields=['status', 'created_at']),
        ]

    def __str__(self):
        return f'[{self.module}.{self.action}] {self.client_tx_id} -> {self.tx_hash or "(pending)"}'
