# Generated by Django 4.2.30 on 2026-04-22 18:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('irg_jr', '0003_gold_assessment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goldassessment',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
