# Generated by Django 4.2.30 on 2026-04-22 18:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_consultant_advertiser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='advertiserprofile',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='consultantprofile',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='role',
            field=models.CharField(choices=[('JEWELER', 'Jeweler'), ('HOUSEHOLD', 'Household (Earmarking)'), ('INVESTOR', 'IRG_GDP/FTR Buyer'), ('RETURNEE', 'Jewelry Returnee'), ('DESIGNER', 'Jewelry Designer'), ('OMBUDSMAN', 'Ombudsman'), ('CONSULTANT', 'Consultant'), ('ADVERTISER', 'Advertiser'), ('MARKETMAKER', 'Market Maker'), ('LICENSEE', 'Licensee'), ('MINTER', 'FTR Minter'), ('TRUSTEE', 'Trustee Banker'), ('ADMIN', 'Administrator')], max_length=20),
        ),
    ]
